package erp.workorder.enums;


public enum PageType {
	
	UNIT(1),
	BOQ(101),
	CATEGORY(102),
	HIGHWAY_BOQ(103),
	CHAINAGE(104),
	CHAINAGE_BOQ_QTY(105),
	STRUCTURE_BOQ_QTY(106),
	WORKORDER(107),
	STRUCTURE(108),
	STRUCTURE_TYPE(109),
	WORKORDER_TYPE(110),
	CONTRACTOR(111),
	WORKORDER_BOQ_WORK(112),
	WORKORDER_TNC(113),
	WORKORDER_TNC_MAPPING(114),
	WORKORDER_CONFIG(115),
	WORKORDER_TNC_TYPE(116),
	CONSOLIDATED_BOQ(117),
	WORKORDER_TYPE_BOQ_TNC_MAP(118),
	HIGHWAY_BOQ_MEASUREMENT(119),
	STRUCTURE_BOQ_MEASUREMENT(120),
	DIESEL_RATE(121);
	
	private int pageId;
	
	PageType(Integer pageId){
		this.pageId = pageId;
	}
	
	public int getPageId() {
		return pageId;
	}

}
